services:
  AUTH_SERVICE:
    host: "localhost"
    port: 5000
    protocol: "http"
    request_per_minute: 15
  USER_SERVICE:
    host: "localhost"
    port: 6000
    protocol: "http"
    request_per_minute: 1
  ORDER_SERVICE:
    host: "localhost"
    port: 7000
    protocol: "http"
    request_per_minute: 50
  INVENTORY_SERVICE:
    host: "localhost"
    port: 8000
    protocol: "http"
    request_per_minute: 10